require('dotenv').config();
const mongoose = require('mongoose');
const User = require('../models/User');
const City = require('../models/City');
const Activity = require('../models/Activity');
const Trip = require('../models/Trip');
const Expense = require('../models/Expense');
const { generateSlug } = require('../utils/slug');

const citiesData = [
  {
    name: 'Mumbai',
    country: 'India',
    region: 'Asia',
    description: 'The vibrant financial powerhouse of India, famous for Bollywood, coastal promenades, colonial architecture, and street cuisine.',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80',
    popularity: 92,
    costIndex: 2,
    latitude: 19.0760,
    longitude: 72.8777,
    recommended: true,
    highlights: ['Gateway of India', 'Marine Drive Sunset', 'Elephanta Caves', 'Colaba Causeway'],
  },
  {
    name: 'Delhi',
    country: 'India',
    region: 'Asia',
    description: 'India’s historic capital blending centuries-old Mughal monuments with bustling modern bazaars and lush gardens.',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
    popularity: 88,
    costIndex: 2,
    latitude: 28.7041,
    longitude: 77.1025,
    recommended: true,
    highlights: ['Red Fort', 'Qutub Minar', 'Chandni Chowk Food Walk', 'Humayun’s Tomb'],
  },
  {
    name: 'Goa',
    country: 'India',
    region: 'Asia',
    description: 'Tropical paradise known for golden beaches, Portuguese heritage architecture, vibrant nightlife, and coastal seafood.',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
    popularity: 95,
    costIndex: 2,
    latitude: 15.2993,
    longitude: 74.1240,
    recommended: true,
    highlights: ['Anjuna Beach', 'Fort Aguada', 'Dudhsagar Waterfalls', 'Fontainhas Heritage Walk'],
  },
  {
    name: 'Jaipur',
    country: 'India',
    region: 'Asia',
    description: 'The Pink City of royalty, boasting magnificent hill forts, opulent palaces, colorful textiles, and rich Rajasthani traditions.',
    image: 'https://images.unsplash.com/photo-1603262110263-fb010d6e75dc?auto=format&fit=crop&w=800&q=80',
    popularity: 90,
    costIndex: 2,
    latitude: 26.9124,
    longitude: 75.7873,
    recommended: true,
    highlights: ['Amber Palace', 'Hawa Mahal', 'City Palace', 'Nahargarh Sunset'],
  },
  {
    name: 'Ahmedabad',
    country: 'India',
    region: 'Asia',
    description: 'India’s first UNESCO World Heritage City, renowned for intricate stepwells, Gandhi’s Sabarmati Ashram, and incredible culinary culture.',
    image: 'https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?auto=format&fit=crop&w=800&q=80',
    popularity: 84,
    costIndex: 1,
    latitude: 23.0225,
    longitude: 72.5714,
    recommended: false,
    highlights: ['Sabarmati Ashram', 'Adalaj Stepwell', 'Manek Chowk Night Market', 'Kankaria Lake'],
  },
  {
    name: 'Bengaluru',
    country: 'India',
    region: 'Asia',
    description: 'The Garden City and Silicon Valley of India, known for pleasant climate, green parks, craft microbreweries, and modern tech hubs.',
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80',
    popularity: 86,
    costIndex: 2,
    latitude: 12.9716,
    longitude: 77.5946,
    recommended: false,
    highlights: ['Lalbagh Botanical Garden', 'Bangalore Palace', 'Cubbon Park', 'Indiranagar Cafes'],
  },
  {
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    description: 'The City of Light, world capital of art, fashion, gastronomy, and iconic monuments along the River Seine.',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    popularity: 98,
    costIndex: 4,
    latitude: 48.8566,
    longitude: 2.3522,
    recommended: true,
    highlights: ['Eiffel Tower Summit', 'Louvre Museum', 'Montmartre & Sacré-Cœur', 'Seine River Cruise'],
  },
  {
    name: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    description: 'Dynamic metropolis rich in royal history, world-class museums, West End theatre, iconic double-deckers, and vibrant boroughs.',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
    popularity: 96,
    costIndex: 4,
    latitude: 51.5074,
    longitude: -0.1278,
    recommended: true,
    highlights: ['Tower Bridge', 'British Museum', 'Westminster Abbey', 'Hyde Park'],
  },
  {
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    description: 'The Eternal City with thousands of years of art and architecture on display, from the Colosseum to the Vatican and gelato piazza life.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
    popularity: 97,
    costIndex: 3,
    latitude: 41.9028,
    longitude: 12.4964,
    recommended: true,
    highlights: ['Colosseum & Forum', 'Vatican Museums', 'Trevi Fountain', 'Trastevere Food Tour'],
  },
  {
    name: 'Dubai',
    country: 'United Arab Emirates',
    region: 'Middle East',
    description: 'Futuristic desert oasis of luxury shopping, ultramodern architecture, desert safaris, and legendary hospitality.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    popularity: 94,
    costIndex: 4,
    latitude: 25.2048,
    longitude: 55.2708,
    recommended: true,
    highlights: ['Burj Khalifa Observation', 'Desert 4x4 Safari', 'Dubai Marina Walk', 'Dubai Mall Fountain'],
  },
  {
    name: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    description: 'Clean, green Garden City blending supertrees, futuristic attractions, multicultural hawker centers, and waterfront luxury.',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80',
    popularity: 93,
    costIndex: 4,
    latitude: 1.3521,
    longitude: 103.8198,
    recommended: true,
    highlights: ['Gardens by the Bay', 'Marina Bay Sands SkyPark', 'Sentosa Island', 'Chinatown Hawker Feast'],
  },
  {
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    description: 'Mesmerizing fusion of neon-lit skyscrapers, historic shrines, anime culture, and unparalleled culinary excellence.',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    popularity: 99,
    costIndex: 4,
    latitude: 35.6762,
    longitude: 139.6503,
    recommended: true,
    highlights: ['Shibuya Crossing', 'Senso-ji Temple', 'Shinjuku Neon Tour', 'Tsukiji Outer Market'],
  },
  {
    name: 'Bangkok',
    country: 'Thailand',
    region: 'Asia',
    description: 'Bustling metropolis famous for ornate golden shrines, buzzing street life, floating markets, and legendary Thai hospitality.',
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=800&q=80',
    popularity: 95,
    costIndex: 2,
    latitude: 13.7563,
    longitude: 100.5018,
    recommended: true,
    highlights: ['Grand Palace', 'Wat Arun', 'Chatuchak Weekend Market', 'Chao Phraya Dinner Cruise'],
  },
  {
    name: 'New York',
    country: 'United States',
    region: 'North America',
    description: 'The City That Never Sleeps, home to iconic skyscrapers, Central Park, Broadway shows, and endless international culture.',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
    popularity: 97,
    costIndex: 5,
    latitude: 40.7128,
    longitude: -74.0060,
    recommended: true,
    highlights: ['Statue of Liberty', 'Central Park Walk', 'Empire State Building', 'Times Square & Broadway'],
  },
  {
    name: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    description: 'Mediterranean seaside paradise famous for Gaudí’s surrealist architecture, golden beaches, and lively tapas culture.',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=800&q=80',
    popularity: 96,
    costIndex: 3,
    latitude: 41.3851,
    longitude: 2.1734,
    recommended: true,
    highlights: ['Sagrada Família', 'Park Güell', 'Gothic Quarter', 'Barceloneta Beach'],
  },
  {
    name: 'Amsterdam',
    country: 'Netherlands',
    region: 'Europe',
    description: 'Historic city of picturesque canal rings, world-renowned art museums, cycling avenues, and charming houseboats.',
    image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=800&q=80',
    popularity: 95,
    costIndex: 4,
    latitude: 52.3676,
    longitude: 4.9041,
    recommended: true,
    highlights: ['Canal Ring Cruise', 'Rijksmuseum', 'Van Gogh Museum', 'Jordaan District'],
  },
  {
    name: 'San Francisco',
    country: 'United States',
    region: 'North America',
    description: 'Iconic bayside metropolis celebrated for the Golden Gate Bridge, vintage cable cars, Victorian houses, and tech innovation.',
    image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=800&q=80',
    popularity: 94,
    costIndex: 5,
    latitude: 37.7749,
    longitude: -122.4194,
    recommended: true,
    highlights: ['Golden Gate Bridge', 'Alcatraz Island', 'Fisherman’s Wharf', 'Lombard Street'],
  },
  {
    name: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    description: 'Tropical island of the gods with emerald rice terraces, cliffside sea temples, pristine surf beaches, and yoga retreats.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    popularity: 98,
    costIndex: 2,
    latitude: -8.4095,
    longitude: 115.1889,
    recommended: true,
    highlights: ['Uluwatu Sunset Temple', 'Tegallalang Rice Terraces', 'Ubud Sacred Monkey Forest', 'Seminyak Beach Club'],
  },
  {
    name: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    description: 'Breathtaking coastal metropolis featuring the world-famous Opera House, sunny surf beaches, and scenic harbor ferries.',
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80',
    popularity: 96,
    costIndex: 4,
    latitude: -33.8688,
    longitude: 151.2093,
    recommended: true,
    highlights: ['Sydney Opera House', 'Bondi to Coogee Coastal Walk', 'Harbour Bridge', 'Manly Ferry Ride'],
  },
  {
    name: 'Cape Town',
    country: 'South Africa',
    region: 'Africa',
    description: 'Dramatic coastal city crowned by Table Mountain, sweeping ocean vistas, African penguin colonies, and scenic winelands.',
    image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=800&q=80',
    popularity: 93,
    costIndex: 2,
    latitude: -33.9249,
    longitude: 18.4241,
    recommended: true,
    highlights: ['Table Mountain Aerial Cableway', 'Boulders Beach Penguins', 'Cape Point', 'Kirstenbosch Gardens'],
  },
  {
    name: 'Cairo',
    country: 'Egypt',
    region: 'Africa',
    description: 'Cradle of ancient civilization, home to the Great Pyramids of Giza, the Sphinx, and tranquil sunset feluccas along the Nile.',
    image: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=800&q=80',
    popularity: 94,
    costIndex: 2,
    latitude: 30.0444,
    longitude: 31.2357,
    recommended: true,
    highlights: ['Great Pyramids of Giza', 'The Great Sphinx', 'Nile River Sunset Felucca', 'Khan el-Khalili Bazaar'],
  },
  {
    name: 'Rio de Janeiro',
    country: 'Brazil',
    region: 'South America',
    description: 'Vibrant Marvelous City known for Christ the Redeemer atop Corcovado, golden Copacabana sands, and passionate samba rhythms.',
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=800&q=80',
    popularity: 92,
    costIndex: 2,
    latitude: -22.9068,
    longitude: -43.1729,
    recommended: true,
    highlights: ['Christ the Redeemer', 'Sugarloaf Mountain Cable Car', 'Copacabana Beach', 'Selarón Steps'],
  },
  {
    name: 'Udaipur',
    country: 'India',
    region: 'Asia',
    description: 'The romantic City of Lakes surrounded by the Aravali hills, marble palaces, and serene boat cruises across Lake Pichola.',
    image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=800&q=80',
    popularity: 91,
    costIndex: 2,
    latitude: 24.5854,
    longitude: 73.7125,
    recommended: true,
    highlights: ['Lake Pichola Boat Cruise', 'City Palace Udaipur', 'Jag Mandir Island', 'Saheliyon-ki-Bari'],
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/globetrotter');
    console.log('[Seed] Connected to MongoDB');

    // Clean existing records
    await User.deleteMany({});
    await City.deleteMany({});
    await Activity.deleteMany({});
    await Trip.deleteMany({});
    await Expense.deleteMany({});
    console.log('[Seed] Cleared existing database collections');

    // 1. Insert Cities
    const insertedCities = await City.insertMany(citiesData);
    console.log(`[Seed] Inserted ${insertedCities.length} cities`);

    const cityMap = {};
    insertedCities.forEach((city) => {
      cityMap[city.name] = city;
    });

    // 2. Generate Activities
    const activitiesData = [
      // Mumbai
      {
        city: cityMap['Mumbai']._id,
        name: 'Gateway of India & Harbor Ferry Tour',
        description: 'Iconic 20th-century monument overlooking the Arabian Sea, followed by a scenic harbor ferry ride.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=600&q=80',
        duration: 2.5,
        estimatedCost: 800,
        rating: 4.8,
        popularity: 95,
        location: 'Apollo Bunder, Colaba',
        recommended: true,
      },
      {
        city: cityMap['Mumbai']._id,
        name: 'South Bombay Street Food Crawl',
        description: 'Sample pav bhaji, bun maska, sev puri, and vada pav across historic cafes and street stalls.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 1200,
        rating: 4.9,
        popularity: 92,
        location: 'Girgaon Chowpatty & Fort',
        recommended: true,
      },
      {
        city: cityMap['Mumbai']._id,
        name: 'Marine Drive Sunset Stroll & Sea Face View',
        description: 'Walk along the famous Queen’s Necklace promenade during magical golden hour.',
        category: 'nature',
        image: 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=600&q=80',
        duration: 1.5,
        estimatedCost: 0,
        rating: 4.7,
        popularity: 96,
        location: 'Marine Drive, Nariman Point',
        recommended: true,
      },
      {
        city: cityMap['Mumbai']._id,
        name: 'Elephanta Island Rock-cut Caves Excursion',
        description: 'UNESCO World Heritage rock-cut cave temples dedicated to Lord Shiva, reached by cruise.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=600&q=80',
        duration: 4,
        estimatedCost: 1500,
        rating: 4.6,
        popularity: 88,
        location: 'Gharapuri Island',
        recommended: false,
      },

      // Delhi
      {
        city: cityMap['Delhi']._id,
        name: 'Old Delhi Heritage & Spice Market Walk',
        description: 'Explore Chandni Chowk, Khari Baoli spice bazaar, and savor Paranthe Wali Gali delicacies.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=600&q=80',
        duration: 3.5,
        estimatedCost: 1000,
        rating: 4.8,
        popularity: 94,
        location: 'Chandni Chowk',
        recommended: true,
      },
      {
        city: cityMap['Delhi']._id,
        name: 'Mughal Architecture Tour (Qutub & Humayun Tomb)',
        description: 'Discover soaring minarets and precursors to the Taj Mahal amidst lush Persian-style gardens.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1592635196078-9fdc757f27f4?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 1200,
        rating: 4.7,
        popularity: 90,
        location: 'Mehrauli & Nizamuddin',
        recommended: true,
      },

      // Goa
      {
        city: cityMap['Goa']._id,
        name: 'Scuba Diving & Watersports at Grand Island',
        description: 'Snorkeling, scuba diving with marine life, and dolphin spotting in Arabian waters.',
        category: 'adventure',
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
        duration: 5,
        estimatedCost: 3500,
        rating: 4.9,
        popularity: 96,
        location: 'Grand Island, Vasco',
        recommended: true,
      },
      {
        city: cityMap['Goa']._id,
        name: 'Fontainhas Latin Quarter Walking Tour',
        description: 'Wander through vibrant pastel Portuguese villas, art galleries, and historic bakeries.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=600&q=80',
        duration: 2,
        estimatedCost: 600,
        rating: 4.7,
        popularity: 89,
        location: 'Panaji',
        recommended: true,
      },
      {
        city: cityMap['Goa']._id,
        name: 'Sunset Beach Shack Seafood Dinner',
        description: 'Fresh grilled kingfish, Goan prawn curry, and chilled drinks under the stars.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80',
        duration: 2.5,
        estimatedCost: 1800,
        rating: 4.8,
        popularity: 93,
        location: 'Anjuna / Calangute Beach',
        recommended: true,
      },

      // Jaipur
      {
        city: cityMap['Jaipur']._id,
        name: 'Amber Fort Elephant Trail & Palace Tour',
        description: 'Spectacular hilltop fortress with ornate mirror halls (Sheesh Mahal) and panoramic mountain views.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1603262110263-fb010d6e75dc?auto=format&fit=crop&w=600&q=80',
        duration: 3.5,
        estimatedCost: 1500,
        rating: 4.9,
        popularity: 97,
        location: 'Amer, Jaipur',
        recommended: true,
      },
      {
        city: cityMap['Jaipur']._id,
        name: 'Royal Rajasthani Thali Experience',
        description: 'Authentic 15-dish traditional banquet featuring Dal Baati Churma, Gatte ki Sabzi, and sweets.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
        duration: 2,
        estimatedCost: 1200,
        rating: 4.8,
        popularity: 91,
        location: 'Chokhi Dhani / MI Road',
        recommended: true,
      },

      // Paris
      {
        city: cityMap['Paris']._id,
        name: 'Eiffel Tower Summit Access & Champagne',
        description: 'Ascend to the top of Paris for breathtaking 360-degree views and an unforgettable sunset toast.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=600&q=80',
        duration: 2.5,
        estimatedCost: 4500,
        rating: 4.9,
        popularity: 99,
        location: 'Champ de Mars',
        recommended: true,
      },
      {
        city: cityMap['Paris']._id,
        name: 'Louvre Museum Guided Masterpieces Tour',
        description: 'Skip the line to marvel at Mona Lisa, Venus de Milo, Winged Victory, and ancient Egyptian halls.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1565099824688-e93eb20fe622?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 5500,
        rating: 4.9,
        popularity: 98,
        location: 'Rue de Rivoli',
        recommended: true,
      },
      {
        city: cityMap['Paris']._id,
        name: 'Montmartre Artists & French Bakery Trail',
        description: 'Cobblestone streets of artists, fresh croissants, macarons, and the view from Sacré-Cœur basilica.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=600&q=80',
        duration: 2.5,
        estimatedCost: 3200,
        rating: 4.8,
        popularity: 93,
        location: '18th Arrondissement',
        recommended: true,
      },

      // London
      {
        city: cityMap['London']._id,
        name: 'Tower of London & Crown Jewels Discovery',
        description: 'Step into 1,000 years of royal intrigue, see the sparkling Crown Jewels and meet Yeoman Warders.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 4000,
        rating: 4.8,
        popularity: 95,
        location: 'St Katharine’s & Wapping',
        recommended: true,
      },
      {
        city: cityMap['London']._id,
        name: 'West End Musical Theatre Night',
        description: 'Immerse in world-class performing arts at London’s historic theatre district.',
        category: 'entertainment',
        image: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 6500,
        rating: 4.9,
        popularity: 96,
        location: 'Covent Garden & Soho',
        recommended: true,
      },

      // Rome
      {
        city: cityMap['Rome']._id,
        name: 'Colosseum & Roman Forum Gladiator Arena Tour',
        description: 'Walk through ancient gladiatorial grounds, the emperors’ palaces on Palatine Hill, and the Senate.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80',
        duration: 3.5,
        estimatedCost: 4800,
        rating: 4.9,
        popularity: 98,
        location: 'Piazza del Colosseo',
        recommended: true,
      },
      {
        city: cityMap['Rome']._id,
        name: 'Authentic Pasta Making & Wine Tasting in Trastevere',
        description: 'Handmade fettuccine and ravioli masterclass with a local Roman chef and organic Italian wines.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 5200,
        rating: 4.9,
        popularity: 94,
        location: 'Trastevere',
        recommended: true,
      },

      // Dubai
      {
        city: cityMap['Dubai']._id,
        name: 'Red Dunes 4x4 Safari, Sandboarding & BBQ Camp',
        description: 'Thrilling dune bashing in the Lahbab desert, camel rides, falconry, and belly dance BBQ dinner.',
        category: 'adventure',
        image: 'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?auto=format&fit=crop&w=600&q=80',
        duration: 6,
        estimatedCost: 6000,
        rating: 4.9,
        popularity: 97,
        location: 'Lahbab Desert',
        recommended: true,
      },
      {
        city: cityMap['Dubai']._id,
        name: 'Burj Khalifa Level 148 At the Top SKY Experience',
        description: 'Stand at the world’s highest outdoor observation deck with luxury lounge access.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80',
        duration: 2,
        estimatedCost: 8500,
        rating: 4.8,
        popularity: 96,
        location: 'Downtown Dubai',
        recommended: true,
      },

      // Tokyo
      {
        city: cityMap['Tokyo']._id,
        name: 'Shibuya Crossing, Harajuku & Meiji Shrine Tour',
        description: 'Experience Tokyo contrast: the world’s busiest scramble crossing, youth fashion, and tranquil forest shrine.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=600&q=80',
        duration: 4,
        estimatedCost: 3800,
        rating: 4.9,
        popularity: 99,
        location: 'Shibuya & Harajuku',
        recommended: true,
      },
      {
        city: cityMap['Tokyo']._id,
        name: 'Tsukiji Market Fresh Sushi Making Masterclass',
        description: 'Select fresh fish at the market and craft nigiri and maki rolls with an experienced sushi master.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80',
        duration: 2.5,
        estimatedCost: 6200,
        rating: 4.9,
        popularity: 95,
        location: 'Tsukiji',
        recommended: true,
      },

      // Singapore
      {
        city: cityMap['Singapore']._id,
        name: 'Gardens by the Bay Supertree Grove & Cloud Forest',
        description: 'Explore the futuristic misty indoor mountain waterfall and walk the OCBC Skyway.',
        category: 'nature',
        image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 3200,
        rating: 4.9,
        popularity: 98,
        location: 'Marina South',
        recommended: true,
      },

      // Bangkok
      {
        city: cityMap['Bangkok']._id,
        name: 'Grand Palace & Wat Pho Reclining Buddha Tour',
        description: 'Magnificent golden temples, emerald Buddha shrines, and traditional Thai massage birthplace.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=600&q=80',
        duration: 3.5,
        estimatedCost: 2200,
        rating: 4.8,
        popularity: 94,
        location: 'Phra Nakhon',
        recommended: true,
      },
      {
        city: cityMap['Bangkok']._id,
        name: 'Bangkok Floating Night Market & Pad Thai Feast',
        description: 'Cruise through bustling canal markets on a wooden longtail boat and taste authentic street pad thai.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 1800,
        rating: 4.9,
        popularity: 96,
        location: 'Amphawa / Damnoen Saduak',
        recommended: true,
      },

      // New York
      {
        city: cityMap['New York']._id,
        name: 'Statue of Liberty & Ellis Island Ferry Tour',
        description: 'Cruising past the Manhattan skyline to the iconic monument of freedom and immigration museum.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=600&q=80',
        duration: 4,
        estimatedCost: 4200,
        rating: 4.8,
        popularity: 97,
        location: 'Battery Park',
        recommended: true,
      },
      {
        city: cityMap['New York']._id,
        name: 'Broadway Musical Theatre & Times Square Glow',
        description: 'Experience dazzling world-class musical theatrical productions in the heart of Midtown Manhattan.',
        category: 'entertainment',
        image: 'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 8500,
        rating: 4.9,
        popularity: 98,
        location: 'Times Square & Theater District',
        recommended: true,
      },
      {
        city: cityMap['New York']._id,
        name: 'Central Park Rowboat & Conservatory Water Walk',
        description: 'Rent classic rowboats at Loeb Boathouse and explore Bow Bridge and Strawberry Fields memorial.',
        category: 'nature',
        image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&w=600&q=80',
        duration: 2.5,
        estimatedCost: 1600,
        rating: 4.8,
        popularity: 95,
        location: 'Central Park',
        recommended: true,
      },

      // Ahmedabad
      {
        city: cityMap['Ahmedabad']._id,
        name: 'Sabarmati Ashram & UNESCO Heritage City Walk',
        description: 'Walk through Mahatma Gandhi’s historic residence and the intricate wooden pol houses of Old Ahmedabad.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1609137144822-12ec1e57c669?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 500,
        rating: 4.9,
        popularity: 95,
        location: 'Ashram Road & Old City',
        recommended: true,
      },
      {
        city: cityMap['Ahmedabad']._id,
        name: 'Manek Chowk Midnight Street Food Safari',
        description: 'Experience the bustling jewel market that transforms into a midnight culinary hub for pav bhaji and chocolate sandwiches.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
        duration: 2,
        estimatedCost: 700,
        rating: 4.8,
        popularity: 94,
        location: 'Manek Chowk',
        recommended: true,
      },
      {
        city: cityMap['Ahmedabad']._id,
        name: 'Sabarmati Riverfront Promenade & Floral Park Cycle',
        description: 'Scenic cycling and walking trail along the tranquil Sabarmati River with modern botanical gardens.',
        category: 'nature',
        image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=600&q=80',
        duration: 2,
        estimatedCost: 300,
        rating: 4.7,
        popularity: 90,
        location: 'Riverfront West',
        recommended: true,
      },

      // Bengaluru
      {
        city: cityMap['Bengaluru']._id,
        name: 'Lalbagh Botanical Garden & Glass House Heritage Tour',
        description: 'Stroll across 240 acres of exotic tropical flora, centuries-old bonsai, and the historic Glass House.',
        category: 'nature',
        image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=600&q=80',
        duration: 2.5,
        estimatedCost: 400,
        rating: 4.8,
        popularity: 91,
        location: 'Mavalli, Bengaluru',
        recommended: true,
      },
      {
        city: cityMap['Bengaluru']._id,
        name: 'Craft Microbrewery Trail & Indiranagar Dining',
        description: 'Taste artisanal ales, fresh stout, and gourmet woodfired sourdough pizza in India’s pub capital.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 2200,
        rating: 4.9,
        popularity: 93,
        location: '100ft Road, Indiranagar',
        recommended: true,
      },

      // More Adventure & Nature across Destinations
      {
        city: cityMap['Jaipur']._id,
        name: 'Sunrise Hot Air Ballooning Over Aravali Forts',
        description: 'Glide gently over majestic desert forts, palaces, and traditional villages at dawn.',
        category: 'adventure',
        image: 'https://images.unsplash.com/photo-1507608869274-d3177c8bb4c7?auto=format&fit=crop&w=600&q=80',
        duration: 4,
        estimatedCost: 12000,
        rating: 5.0,
        popularity: 98,
        location: 'Kukas / Amber',
        recommended: true,
      },
      {
        city: cityMap['Tokyo']._id,
        name: 'Akihabara VR Gaming & Retro Arcade Odyssey',
        description: 'Dive into cutting-edge virtual reality battle arenas and classic arcade gaming nostalgia.',
        category: 'entertainment',
        image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 4200,
        rating: 4.8,
        popularity: 96,
        location: 'Electric Town, Akihabara',
        recommended: true,
      },
      {
        city: cityMap['Tokyo']._id,
        name: 'Shinjuku Gyoen National Garden & Tea Pavilion',
        description: 'Tranquil Japanese traditional landscaping, ponds, and peaceful matcha green tea ceremonies.',
        category: 'nature',
        image: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?auto=format&fit=crop&w=600&q=80',
        duration: 2.5,
        estimatedCost: 800,
        rating: 4.9,
        popularity: 97,
        location: 'Shinjuku',
        recommended: true,
      },
      {
        city: cityMap['Singapore']._id,
        name: 'Universal Studios Sentosa Island Thrill Rides',
        description: 'Adrenaline-pumping roller coasters, 3D transformer rides, and Hollywood movie themed zones.',
        category: 'entertainment',
        image: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=600&q=80',
        duration: 6,
        estimatedCost: 5500,
        rating: 4.9,
        popularity: 97,
        location: 'Resorts World Sentosa',
        recommended: true,
      },
      {
        city: cityMap['Goa']._id,
        name: 'Dudhsagar Waterfalls Jungle Jeep Safari & Spice Trek',
        description: 'Trek to the majestic 4-tiered cascading waterfall nestled deep in the Bhagwan Mahavir Wildlife Sanctuary.',
        category: 'nature',
        image: 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?auto=format&fit=crop&w=600&q=80',
        duration: 6,
        estimatedCost: 2800,
        rating: 4.9,
        popularity: 95,
        location: 'Sonaulim, South Goa',
        recommended: true,
      },
      {
        city: cityMap['Paris']._id,
        name: 'Moulin Rouge Legendary Cabaret & Champagne Night',
        description: 'The world-famous Féerie cabaret show with spectacular acrobats, French cancan, and fine champagne.',
        category: 'entertainment',
        image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 9500,
        rating: 4.8,
        popularity: 96,
        location: 'Boulevard de Clichy',
        recommended: true,
      },
      {
        city: cityMap['Rome']._id,
        name: 'Vatican Museums & Sistine Chapel Exclusive Early Access',
        description: 'Gaze upon Michelangelo’s breathtaking ceiling and Raphael’s Rooms with expert art historians.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1543429776-2782fc8e1acd?auto=format&fit=crop&w=600&q=80',
        duration: 3.5,
        estimatedCost: 5800,
        rating: 4.9,
        popularity: 99,
        location: 'Viale Vaticano',
        recommended: true,
      },
      {
        city: cityMap['London']._id,
        name: 'Thames Rockets High-Speed RIB Speedboat Adventure',
        description: 'High-speed thrill ride on the River Thames weaving past Big Ben, London Eye, and Canary Wharf.',
        category: 'adventure',
        image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=600&q=80',
        duration: 1.5,
        estimatedCost: 4500,
        rating: 4.9,
        popularity: 93,
        location: 'Boardwalk Pier, London',
        recommended: true,
      },
      {
        city: cityMap['Dubai']._id,
        name: 'Palm Jumeirah Tandem Skydiving Jump',
        description: 'Freefall from 13,000 feet above the world-famous palm-shaped island with panoramic Gulf views.',
        category: 'adventure',
        image: 'https://images.unsplash.com/photo-1521673461164-de300ebcfb17?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 24000,
        rating: 5.0,
        popularity: 99,
        location: 'Skydive Dubai, Palm Dropzone',
        recommended: true,
      },
      {
        city: cityMap['Delhi']._id,
        name: 'Kingdom of Dreams Bollywood Musical Spectacular',
        description: 'Live theatrical song, dance, acrobatic displays, and cultural cuisine from every Indian state.',
        category: 'entertainment',
        image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
        duration: 3.5,
        estimatedCost: 3500,
        rating: 4.8,
        popularity: 91,
        location: 'Sector 29, Gurugram / NCR',
        recommended: true,
      },

      // Barcelona
      {
        city: cityMap['Barcelona']._id,
        name: 'Sagrada Família Fast-Track & Towers Access Tour',
        description: 'Marvel at Antoni Gaudí’s awe-inspiring basilica, stained-glass light reflections, and skyline views.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=600&q=80',
        duration: 2.5,
        estimatedCost: 3800,
        rating: 4.9,
        popularity: 98,
        location: 'Eixample, Barcelona',
        recommended: true,
      },
      {
        city: cityMap['Barcelona']._id,
        name: 'Gothic Quarter Tapas Crawl & Sangria Tasting',
        description: 'Taste authentic jamón ibérico, patatas bravas, and regional wines through medieval alleys.',
        category: 'food',
        image: 'https://images.unsplash.com/photo-1515443961218-a51367888e4b?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 4200,
        rating: 4.9,
        popularity: 96,
        location: 'Barri Gòtic',
        recommended: true,
      },

      // Amsterdam
      {
        city: cityMap['Amsterdam']._id,
        name: 'Historic UNESCO Canal Cruise with Dutch Cheese & Wine',
        description: 'Glide past 17th-century merchant houses, picturesque bridges, and illuminated canals at dusk.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1512470876302-972faa2aa9a4?auto=format&fit=crop&w=600&q=80',
        duration: 2,
        estimatedCost: 3200,
        rating: 4.8,
        popularity: 95,
        location: 'Singel Canal',
        recommended: true,
      },

      // San Francisco
      {
        city: cityMap['San Francisco']._id,
        name: 'Golden Gate Bridge & Alcatraz Island Combo Tour',
        description: 'Walk across the iconic suspension bridge and cruise to the legendary former federal penitentiary.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=600&q=80',
        duration: 5,
        estimatedCost: 6500,
        rating: 4.9,
        popularity: 97,
        location: 'Pier 33, Fisherman’s Wharf',
        recommended: true,
      },

      // Bali
      {
        city: cityMap['Bali']._id,
        name: 'Uluwatu Clifftop Sunset Temple & Kecak Fire Dance',
        description: 'Perched 70 meters above roaring Indian Ocean waves with an unforgettable traditional fire chant.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
        duration: 4,
        estimatedCost: 1800,
        rating: 4.9,
        popularity: 98,
        location: 'Pecatu, South Bali',
        recommended: true,
      },
      {
        city: cityMap['Bali']._id,
        name: 'Ayung River White Water Rafting & Waterfall Swim',
        description: 'Paddle through lush tropical rainforest valleys, hidden waterfalls, and carved river stone cliffs.',
        category: 'adventure',
        image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
        duration: 4.5,
        estimatedCost: 2400,
        rating: 4.8,
        popularity: 95,
        location: 'Ubud, Bali',
        recommended: true,
      },

      // Sydney
      {
        city: cityMap['Sydney']._id,
        name: 'Sydney Opera House Architectural Tour & Harbour Cruise',
        description: 'Explore the world’s most recognized performing arts center with spectacular harbor backdrop.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 4800,
        rating: 4.9,
        popularity: 97,
        location: 'Bennelong Point, Sydney',
        recommended: true,
      },

      // Cape Town
      {
        city: cityMap['Cape Town']._id,
        name: 'Table Mountain Rotating Cableway & Sunset Lookout',
        description: 'Ride 360-degree rotating cable car to the flat plateau for dramatic Atlantic and city views.',
        category: 'nature',
        image: 'https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=600&q=80',
        duration: 3,
        estimatedCost: 2200,
        rating: 4.9,
        popularity: 96,
        location: 'Table Mountain National Park',
        recommended: true,
      },

      // Cairo
      {
        city: cityMap['Cairo']._id,
        name: 'Giza Great Pyramids & Sphinx Camel Trek Adventure',
        description: 'Explore the last surviving Wonder of the Ancient World on camelback across golden sands.',
        category: 'culture',
        image: 'https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=600&q=80',
        duration: 4.5,
        estimatedCost: 2800,
        rating: 4.9,
        popularity: 99,
        location: 'Al Haram, Giza',
        recommended: true,
      },

      // Rio de Janeiro
      {
        city: cityMap['Rio de Janeiro']._id,
        name: 'Christ the Redeemer & Corcovado Mountain Train',
        description: 'Ride through Tijuca Rainforest to the summit overlooking Guanabara Bay and Sugarloaf.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=600&q=80',
        duration: 3.5,
        estimatedCost: 3200,
        rating: 4.8,
        popularity: 96,
        location: 'Alto da Boa Vista',
        recommended: true,
      },

      // Udaipur
      {
        city: cityMap['Udaipur']._id,
        name: 'Sunset Boat Cruise on Lake Pichola & Jag Mandir Island',
        description: 'Romantic royal boat ride past marble ghats and the floating Taj Lake Palace at sunset.',
        category: 'sightseeing',
        image: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&w=600&q=80',
        duration: 2,
        estimatedCost: 1200,
        rating: 4.9,
        popularity: 94,
        location: 'Lake Pichola Ghats',
        recommended: true,
      },
    ];

    const insertedActivities = await Activity.insertMany(activitiesData);
    console.log(`[Seed] Inserted ${insertedActivities.length} activities`);

    // 3. Create Users
    const demoTraveler = await User.create({
      name: 'Aarav Patel',
      email: 'traveler@globetrotter.com',
      password: 'password123',
      profilePhoto: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80',
      languagePreference: 'English',
      role: 'user',
      savedDestinations: [cityMap['Paris']._id, cityMap['Goa']._id, cityMap['Tokyo']._id],
      isActive: true,
    });

    const demoAdmin = await User.create({
      name: 'Admin Chief',
      email: 'admin@globetrotter.com',
      password: 'password123',
      profilePhoto: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=400&q=80',
      languagePreference: 'English',
      role: 'admin',
      savedDestinations: [cityMap['Rome']._id, cityMap['London']._id],
      isActive: true,
    });

    const userPriya = await User.create({
      name: 'Priya Sharma',
      email: 'priya.sharma@example.com',
      password: 'password123',
      profilePhoto: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
      languagePreference: 'Hindi',
      role: 'user',
      savedDestinations: [cityMap['Jaipur']._id],
      isActive: true,
    });

    console.log('[Seed] Created Demo Users (traveler@globetrotter.com, admin@globetrotter.com, priya.sharma@example.com)');

    // 4. Create Pre-built Rich Trips for Demo Traveler
    const today = new Date();
    const trip1Start = new Date(today);
    trip1Start.setDate(today.getDate() + 10);
    const trip1End = new Date(today);
    trip1End.setDate(today.getDate() + 20);

    const trip1 = new Trip({
      user: demoTraveler._id,
      name: 'European Odyssey 2026',
      description: 'Dream multi-city tour through Paris, Rome, and London experiencing art, gastronomy, and historic landmarks.',
      coverPhoto: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
      startDate: trip1Start,
      endDate: trip1End,
      currency: 'INR',
      totalBudget: 250000,
      isPublic: true,
      publicSlug: 'european-odyssey-2026',
      status: 'Upcoming',
      stops: [
        {
          city: cityMap['Paris']._id,
          cityName: 'Paris',
          country: 'France',
          image: cityMap['Paris'].image,
          startDate: trip1Start,
          endDate: new Date(new Date(trip1Start).setDate(trip1Start.getDate() + 3)),
          order: 0,
          notes: 'Stay at Boutique Hotel in Le Marais. Book museum passes in advance.',
          activities: [
            {
              name: 'Eiffel Tower Summit Access & Champagne',
              description: 'Ascend to the top of Paris for sunset champagne.',
              category: 'sightseeing',
              image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=600&q=80',
              time: '17:30',
              duration: 2.5,
              cost: 4500,
              notes: 'Arrive 20 mins before slot.',
              date: trip1Start,
            },
            {
              name: 'Louvre Museum Guided Masterpieces Tour',
              description: 'Explore Mona Lisa and ancient antiquities.',
              category: 'culture',
              image: 'https://images.unsplash.com/photo-1565099824688-e93eb20fe622?auto=format&fit=crop&w=600&q=80',
              time: '10:00',
              duration: 3,
              cost: 5500,
              notes: 'Enter through Carrousel entrance.',
              date: new Date(new Date(trip1Start).setDate(trip1Start.getDate() + 1)),
            },
          ],
          expenses: [
            { category: 'stay', description: 'Hotel Marais (3 nights)', amount: 45000, currency: 'INR', date: trip1Start },
            { category: 'transport', description: 'Metro Pass & Airport RER', amount: 6000, currency: 'INR', date: trip1Start },
            { category: 'meals', description: 'Bistro dining & pastries', amount: 15000, currency: 'INR', date: trip1Start },
          ],
        },
        {
          city: cityMap['Rome']._id,
          cityName: 'Rome',
          country: 'Italy',
          image: cityMap['Rome'].image,
          startDate: new Date(new Date(trip1Start).setDate(trip1Start.getDate() + 4)),
          endDate: new Date(new Date(trip1Start).setDate(trip1Start.getDate() + 7)),
          order: 1,
          notes: 'Flight from Paris to Rome. Try authentic carbonara and gelato at Giolitti.',
          activities: [
            {
              name: 'Colosseum & Roman Forum Gladiator Arena Tour',
              description: 'Ancient arena floor and Palatine Hill ruins.',
              category: 'sightseeing',
              image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80',
              time: '09:30',
              duration: 3.5,
              cost: 4800,
              notes: 'Wear comfortable walking shoes.',
              date: new Date(new Date(trip1Start).setDate(trip1Start.getDate() + 4)),
            },
            {
              name: 'Authentic Pasta Making & Wine Tasting in Trastevere',
              description: 'Handmade pasta masterclass with chef.',
              category: 'food',
              image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
              time: '18:00',
              duration: 3,
              cost: 5200,
              notes: 'Dinner included!',
              date: new Date(new Date(trip1Start).setDate(trip1Start.getDate() + 5)),
            },
          ],
          expenses: [
            { category: 'stay', description: 'Trastevere Guest House (3 nights)', amount: 38000, currency: 'INR', date: trip1Start },
            { category: 'transport', description: 'Flight Paris to Rome', amount: 12000, currency: 'INR', date: trip1Start },
            { category: 'meals', description: 'Gelato, pizza, and Italian wine', amount: 12000, currency: 'INR', date: trip1Start },
          ],
        },
      ],
    });

    trip1.recalculate();
    await trip1.save();

    // Trip 2: Indian Heritage Tour
    const trip2Start = new Date(today);
    trip2Start.setDate(today.getDate() + 30);
    const trip2End = new Date(today);
    trip2End.setDate(today.getDate() + 37);

    const trip2 = new Trip({
      user: demoTraveler._id,
      name: 'Royal Heritage & Coastal Escape',
      description: 'A magical journey connecting royal palaces of Jaipur with tropical golden beaches of Goa.',
      coverPhoto: 'https://images.unsplash.com/photo-1603262110263-fb010d6e75dc?auto=format&fit=crop&w=1200&q=80',
      startDate: trip2Start,
      endDate: trip2End,
      currency: 'INR',
      totalBudget: 75000,
      isPublic: true,
      publicSlug: 'royal-heritage-coastal-escape',
      status: 'Upcoming',
      stops: [
        {
          city: cityMap['Jaipur']._id,
          cityName: 'Jaipur',
          country: 'India',
          image: cityMap['Jaipur'].image,
          startDate: trip2Start,
          endDate: new Date(new Date(trip2Start).setDate(trip2Start.getDate() + 3)),
          order: 0,
          notes: 'Explore heritage markets and forts.',
          activities: [
            {
              name: 'Amber Fort Elephant Trail & Palace Tour',
              description: 'Sheesh Mahal mirror palace visit.',
              category: 'sightseeing',
              image: 'https://images.unsplash.com/photo-1603262110263-fb010d6e75dc?auto=format&fit=crop&w=600&q=80',
              time: '09:00',
              duration: 3,
              cost: 1500,
              date: trip2Start,
            },
            {
              name: 'Royal Rajasthani Thali Experience',
              description: 'Authentic 15-dish feast.',
              category: 'food',
              image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
              time: '19:30',
              duration: 2,
              cost: 1200,
              date: trip2Start,
            },
          ],
          expenses: [
            { category: 'stay', description: 'Heritage Haveli Stay', amount: 14000, currency: 'INR', date: trip2Start },
            { category: 'transport', description: 'Private Cab Transfers', amount: 5000, currency: 'INR', date: trip2Start },
            { category: 'meals', description: 'Local snacks & chai', amount: 3000, currency: 'INR', date: trip2Start },
          ],
        },
        {
          city: cityMap['Goa']._id,
          cityName: 'Goa',
          country: 'India',
          image: cityMap['Goa'].image,
          startDate: new Date(new Date(trip2Start).setDate(trip2Start.getDate() + 4)),
          endDate: trip2End,
          order: 1,
          notes: 'Beach time and scuba diving.',
          activities: [
            {
              name: 'Scuba Diving & Watersports at Grand Island',
              description: 'Snorkeling and coral reef dive.',
              category: 'adventure',
              image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=600&q=80',
              time: '08:00',
              duration: 5,
              cost: 3500,
              date: new Date(new Date(trip2Start).setDate(trip2Start.getDate() + 4)),
            },
          ],
          expenses: [
            { category: 'stay', description: 'Beachside Villa Resort', amount: 18000, currency: 'INR', date: trip2Start },
            { category: 'meals', description: 'Seafood shacks & drinks', amount: 6000, currency: 'INR', date: trip2Start },
          ],
        },
      ],
    });

    trip2.recalculate();
    await trip2.save();

    console.log('[Seed] Created Sample Trips with stops, activities, and budget expenses');
    console.log('----------------------------------------------------');
    console.log('SEED COMPLETE! Demo Credentials:');
    console.log('User: traveler@globetrotter.com / password123');
    console.log('Admin: admin@globetrotter.com / password123');
    console.log('----------------------------------------------------');

    process.exit(0);
  } catch (error) {
    console.error('[Seed] Error during seeding:', error);
    process.exit(1);
  }
};

seedDB();
